RichFaces/richfaces-distribution-4.5.0.CR2/richfaces-distribution-4.5.0.CR2/examples/richfaces-showcase/src/main/java/org/richfaces/demo/dragdrop/DragDropBean.java
package org.richfaces.demo.dragdrop;

import static org.richfaces.demo.dragdrop.Framework.Family.cf;
import static org.richfaces.demo.dragdrop.Framework.Family.dotNet;
import static org.richfaces.demo.dragdrop.Framework.Family.php;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.richfaces.demo.dragdrop.Framework.Family;

import com.google.common.base.Predicate;
import com.google.common.collect.Collections2;
import com.google.common.collect.Lists;

@ManagedBean
@ViewScoped
public class DragDropBean implements Serializable {
    private static final long serialVersionUID = 1416925735640720492L;
    private static final FrameworkFamilyPredicate CF_PREDICATE = new FrameworkFamilyPredicate(cf);
    private static final FrameworkFamilyPredicate DOT_NET_PREDICATE = new FrameworkFamilyPredicate(dotNet);
    private static final FrameworkFamilyPredicate PHP_PREDICATE = new FrameworkFamilyPredicate(php);

    private static final class FrameworkFamilyPredicate implements Predicate<Framework> {
        private Framework.Family family;

        public FrameworkFamilyPredicate(Family family) {
            super();
            this.family = family;
        }

        public boolean apply(Framework input) {
            return family.equals(input.getFamily());
        }
    }

    private List<Framework> source;
    private List<Framework> target;

    public DragDropBean() {
        initList();
    }

    public Collection<Framework> getSource() {
        return source;
    }

    public Collection<Framework> getTarget() {
        return target;
    }

    public List<Framework> getTargetPHP() {
        return Lists.newLinkedList(Collections2.filter(target, PHP_PREDICATE));
    }

    public List<Framework> getTargetDotNet() {
        return Lists.newLinkedList(Collections2.filter(target, DOT_NET_PREDICATE));
    }

    public List<Framework> getTargetCF() {
        return Lists.newLinkedList(Collections2.filter(target, CF_PREDICATE));
    }

    public void moveFramework(Framework framework) {
        source.remove(framework);
        target.add(framework);
    }

    public void reset() {
        initList();
    }

    private void initList() {
        source = Lists.newArrayList();
        target = Lists.newArrayList();

        source.add(new Framework("Flexible Ajax", php));
        source.add(new Framework("ajaxCFC", cf));
        source.add(new Framework("AJAXEngine", dotNet));
        source.add(new Framework("AjaxAC", php));
        source.add(new Framework("MonoRail", dotNet));
        source.add(new Framework("wddxAjax", cf));
        source.add(new Framework("AJAX AGENT", php));
        source.add(new Framework("FastPage", dotNet));
        source.add(new Framework("JSMX", cf));
        source.add(new Framework("PAJAJ", php));
        source.add(new Framework("Symfony", php));
        source.add(new Framework("PowerWEB", dotNet));
    }
}

RichFaces/richfaces-distribution-4.5.0.CR2/richfaces-distribution-4.5.0.CR2/examples/richfaces-showcase/src/main/java/org/richfaces/demo/dragdrop/DragDropEventBean.java
package org.richfaces.demo.dragdrop;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import org.richfaces.event.DropEvent;
import org.richfaces.event.DropListener;

@ManagedBean
@RequestScoped
public class DragDropEventBean implements DropListener {
    @ManagedProperty(value = "#{dragDropBean}")
    private DragDropBean dragDropBean;

    public void setDragDropBean(DragDropBean dragDropBean) {
        this.dragDropBean = dragDropBean;
    }

    public void processDrop(DropEvent event) {
        dragDropBean.moveFramework((Framework) event.getDragValue());
    }
}

RichFaces/richfaces-distribution-4.5.0.CR2/richfaces-distribution-4.5.0.CR2/examples/richfaces-showcase/src/main/webapp/richfaces/dragDrop/samples/dragDrop-sample.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
    xmlns:rich="http://richfaces.org/rich">

    <h:outputStylesheet>
        .panelc { width:25%; }
        .valign { vertical-align:top; }
        .dropTargetPanel { width: 90%; }
        .footerClass {
        text-align: center;
        padding-top: 5px;
        }
        .rf-ind-drag{
        font-size:11px;
        cursor:pointer;
        width:100px;
        border:1px solid gray;
        padding:2px
        }
        .rf-ind-acpt{border:2px solid green}
        .rf-ind-rejt{border:2px solid red}
    </h:outputStylesheet>
    <h:form id="form">

        <h:panelGrid columnClasses="panelc valign, valign, valign, valign" columns="4" width="100%">

            <rich:panel style="width:133px">
                <f:facet name="header">
                    <h:outputText value="Source List" />
                </f:facet>
                <h:dataTable id="src" columns="1" value="#{dragDropBean.source}" var="fm" footerClass="footerClass">
                    <h:column>
                        <a4j:outputPanel layout="block" styleClass="rf-ind-drag">
                            <rich:dragSource type="#{fm.family}" dragValue="#{fm}" />
                            <h:outputText value="#{fm.name}"></h:outputText>
                        </a4j:outputPanel>
                    </h:column>
                    <f:facet name="footer">
                        <a4j:commandButton action="#{dragDropBean.reset}" value="Start Over"
                            render="src,phptable,cftable,dnettable" />
                    </f:facet>
                </h:dataTable>
            </rich:panel>

            <rich:panel styleClass="dropTargetPanel">
                <f:facet name="header">
                    <h:outputText value="PHP Frameworks" />
                </f:facet>
                <rich:dropTarget acceptedTypes="php" dropValue="PHP" dropListener="#{dragDropEventBean.processDrop}"
                    render="phptable, src" />

                <h:dataTable id="phptable" columns="1" value="#{dragDropBean.targetPHP}" var="fm">
                    <h:column>
                        <h:outputText value="#{fm.name}"></h:outputText>
                    </h:column>
                </h:dataTable>


            </rich:panel>

            <rich:panel styleClass="dropTargetPanel">
                <f:facet name="header">
                    <h:outputText value=".NET Frameworks" />
                </f:facet>
                <rich:dropTarget acceptedTypes="dotNet" dropValue="DNET" dropListener="#{dragDropEventBean.processDrop}"
                    render="dnettable, src" />

                <h:dataTable id="dnettable" columns="1" value="#{dragDropBean.targetDotNet}" var="fm">
                    <h:column>
                        <h:outputText value="#{fm.name}"></h:outputText>
                    </h:column>
                </h:dataTable>


            </rich:panel>

            <rich:panel styleClass="dropTargetPanel">
                <f:facet name="header">
                    <h:outputText value="ColdFusion Frameworks" />
                </f:facet>
                <rich:dropTarget acceptedTypes="cf" dropValue="CF" dropListener="#{dragDropEventBean.processDrop}"
                    render="cftable, src" />

                <h:dataTable id="cftable" columns="1" value="#{dragDropBean.targetCF}" var="fm">
                    <h:column>
                        <h:outputText value="#{fm.name}"></h:outputText>
                    </h:column>
                </h:dataTable>
            </rich:panel>
        </h:panelGrid>

    </h:form>
    <a4j:outputPanel ajaxRendered="true">
        <h:messages></h:messages>
    </a4j:outputPanel>
</ui:composition>

RichFaces/richfaces-distribution-4.5.0.CR2/richfaces-distribution-4.5.0.CR2/examples/richfaces-showcase/src/main/webapp/richfaces/dragDrop/samples/dragIndicator-sample.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j"
    xmlns:rich="http://richfaces.org/rich">

    <h:outputStylesheet>
        .panelc { width:25%; }
        .valign { vertical-align:top; }
        .dropTargetPanel { width: 90%; }
        .footerClass {
        text-align: center;
        padding-top: 5px;
        }

        .default{
        font-size:11px;
        cursor:pointer;
        width:100px;
        border:1px solid gray;
        padding:2px
        }
        .rf-ind-drag.default{
        padding-left:30px;
        background-image: url("#{facesContext.externalContext.requestContextPath}/images/dnd/default.gif");
        background-position: 5px;
        background-repeat: no-repeat;
        }
        .rf-ind-drag.accept{
        background-image: url("#{facesContext.externalContext.requestContextPath}/images/dnd/accept.gif");
        background-position: 5px;
        background-repeat: no-repeat;
        border:2px solid green
        }
        .rf-ind-drag.reject{
        border:2px solid red;
        background-image: url("#{facesContext.externalContext.requestContextPath}/images/dnd/reject.gif");
        background-position: 5px;
        background-repeat: no-repeat;
        }
    </h:outputStylesheet>
    <rich:dragIndicator id="ind" acceptClass="accept" rejectClass="reject" draggingClass="default">
        Drag the item to proper area..
    </rich:dragIndicator>
    <h:form id="form">

        <h:panelGrid columnClasses="panelc valign, valign, valign, valign" columns="4" width="100%">

            <rich:panel style="width:133px">
                <f:facet name="header">
                    <h:outputText value="Source List" />
                </f:facet>
                <h:dataTable id="src" columns="1" value="#{dragDropBean.source}" var="fm" footerClass="footerClass">
                    <h:column>
                        <a4j:outputPanel layout="block" styleClass="default">
                            <rich:dragSource type="#{fm.family}" dragIndicator="ind" dragValue="#{fm}" />
                            <h:outputText value="#{fm.name}"></h:outputText>
                        </a4j:outputPanel>
                    </h:column>
                    <f:facet name="footer">
                        <a4j:commandButton action="#{dragDropBean.reset}" value="Start Over"
                            render="src,phptable,cftable,dnettable" />
                    </f:facet>
                </h:dataTable>
            </rich:panel>

            <rich:panel styleClass="dropTargetPanel">
                <f:facet name="header">
                    <h:outputText value="PHP Frameworks" />
                </f:facet>
                <rich:dropTarget acceptedTypes="php" dropValue="PHP" dropListener="#{dragDropEventBean.processDrop}"
                    render="phptable, src" />

                <h:dataTable id="phptable" columns="1" value="#{dragDropBean.targetPHP}" var="fm">
                    <h:column>
                        <h:outputText value="#{fm.name}"></h:outputText>
                    </h:column>
                </h:dataTable>


            </rich:panel>

            <rich:panel styleClass="dropTargetPanel">
                <f:facet name="header">
                    <h:outputText value=".NET Frameworks" />
                </f:facet>
                <rich:dropTarget acceptedTypes="dotNet" dropValue="DNET" dropListener="#{dragDropEventBean.processDrop}"
                    render="dnettable, src" />

                <h:dataTable id="dnettable" columns="1" value="#{dragDropBean.targetDotNet}" var="fm">
                    <h:column>
                        <h:outputText value="#{fm.name}"></h:outputText>
                    </h:column>
                </h:dataTable>


            </rich:panel>

            <rich:panel styleClass="dropTargetPanel">
                <f:facet name="header">
                    <h:outputText value="ColdFusion Frameworks" />
                </f:facet>
                <rich:dropTarget acceptedTypes="cf" dropValue="CF" dropListener="#{dragDropEventBean.processDrop}"
                    render="cftable, src" />

                <h:dataTable id="cftable" columns="1" value="#{dragDropBean.targetCF}" var="fm">
                    <h:column>
                        <h:outputText value="#{fm.name}"></h:outputText>
                    </h:column>
                </h:dataTable>
            </rich:panel>
        </h:panelGrid>

    </h:form>
    <a4j:outputPanel ajaxRendered="true">
        <h:messages></h:messages>
    </a4j:outputPanel>
</ui:composition>